[package]
name = "tokio-tungstenite-0-25"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tokio-tungstenite = "0.25.0"
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"

[profile.release]
debug = true
